# Generated by Django 2.1.3 on 2018-11-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloguser',
            old_name='nickname',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='bloguser',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='bloguser',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='bloguser',
            name='slug',
        ),
        migrations.AddField(
            model_name='bloguser',
            name='gender',
            field=models.CharField(choices=[('N', 'Not specified'), ('M', 'Male'), ('F', 'Female')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='email',
            field=models.EmailField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='firstname',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='lastname',
            field=models.CharField(max_length=16),
        ),
    ]
